/*
 * This file is generated by jOOQ.
*/
package com.warumono.databases.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorBook implements Serializable {

    private static final long serialVersionUID = -1633391532;

    private Long authorId;
    private Long bookId;

    public AuthorBook() {}

    public AuthorBook(AuthorBook value) {
        this.authorId = value.authorId;
        this.bookId = value.bookId;
    }

    public AuthorBook(
        Long authorId,
        Long bookId
    ) {
        this.authorId = authorId;
        this.bookId = bookId;
    }

    public Long getAuthorId() {
        return this.authorId;
    }

    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    public Long getBookId() {
        return this.bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthorBook (");

        sb.append(authorId);
        sb.append(", ").append(bookId);

        sb.append(")");
        return sb.toString();
    }
}
