/*
 * This file is generated by jOOQ.
*/
package com.warumono.databases.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_A81B4C44_FE4E_47E0_B648_1647AA0F9CAC</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_A81B4C44_FE4E_47E0_B648_1647AA0F9CAC = new SequenceImpl<Long>("SYSTEM_SEQUENCE_A81B4C44_FE4E_47E0_B648_1647AA0F9CAC", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_F67C552D_54B0_498A_90FD_0F7F3B747F29</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_F67C552D_54B0_498A_90FD_0F7F3B747F29 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_F67C552D_54B0_498A_90FD_0F7F3B747F29", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
