/*
 * This file is generated by jOOQ.
*/
package com.warumono.databases.public_;


import com.warumono.databases.public_.tables.Author;
import com.warumono.databases.public_.tables.AuthorBook;
import com.warumono.databases.public_.tables.Book;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public static final Author AUTHOR = com.warumono.databases.public_.tables.Author.AUTHOR;

    /**
     * The table <code>PUBLIC.AUTHOR_BOOK</code>.
     */
    public static final AuthorBook AUTHOR_BOOK = com.warumono.databases.public_.tables.AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>PUBLIC.BOOK</code>.
     */
    public static final Book BOOK = com.warumono.databases.public_.tables.Book.BOOK;
}
