/*
 * This file is generated by jOOQ.
*/
package com.warumono.databases.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Help implements Serializable {

    private static final long serialVersionUID = 1337635773;

    private Integer id;
    private String  section;
    private String  topic;
    private String  syntax;
    private String  text;

    public Help() {}

    public Help(Help value) {
        this.id = value.id;
        this.section = value.section;
        this.topic = value.topic;
        this.syntax = value.syntax;
        this.text = value.text;
    }

    public Help(
        Integer id,
        String  section,
        String  topic,
        String  syntax,
        String  text
    ) {
        this.id = id;
        this.section = section;
        this.topic = topic;
        this.syntax = syntax;
        this.text = text;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSection() {
        return this.section;
    }

    public void setSection(String section) {
        this.section = section;
    }

    public String getTopic() {
        return this.topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    public String getSyntax() {
        return this.syntax;
    }

    public void setSyntax(String syntax) {
        this.syntax = syntax;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Help (");

        sb.append(id);
        sb.append(", ").append(section);
        sb.append(", ").append(topic);
        sb.append(", ").append(syntax);
        sb.append(", ").append(text);

        sb.append(")");
        return sb.toString();
    }
}
