/*
 * This file is generated by jOOQ.
*/
package com.warumono.databases.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rights implements Serializable {

    private static final long serialVersionUID = 2103264537;

    private String  grantee;
    private String  granteetype;
    private String  grantedrole;
    private String  rights;
    private String  tableSchema;
    private String  tableName;
    private Integer id;

    public Rights() {}

    public Rights(Rights value) {
        this.grantee = value.grantee;
        this.granteetype = value.granteetype;
        this.grantedrole = value.grantedrole;
        this.rights = value.rights;
        this.tableSchema = value.tableSchema;
        this.tableName = value.tableName;
        this.id = value.id;
    }

    public Rights(
        String  grantee,
        String  granteetype,
        String  grantedrole,
        String  rights,
        String  tableSchema,
        String  tableName,
        Integer id
    ) {
        this.grantee = grantee;
        this.granteetype = granteetype;
        this.grantedrole = grantedrole;
        this.rights = rights;
        this.tableSchema = tableSchema;
        this.tableName = tableName;
        this.id = id;
    }

    public String getGrantee() {
        return this.grantee;
    }

    public void setGrantee(String grantee) {
        this.grantee = grantee;
    }

    public String getGranteetype() {
        return this.granteetype;
    }

    public void setGranteetype(String granteetype) {
        this.granteetype = granteetype;
    }

    public String getGrantedrole() {
        return this.grantedrole;
    }

    public void setGrantedrole(String grantedrole) {
        this.grantedrole = grantedrole;
    }

    public String getRights() {
        return this.rights;
    }

    public void setRights(String rights) {
        this.rights = rights;
    }

    public String getTableSchema() {
        return this.tableSchema;
    }

    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }

    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rights (");

        sb.append(grantee);
        sb.append(", ").append(granteetype);
        sb.append(", ").append(grantedrole);
        sb.append(", ").append(rights);
        sb.append(", ").append(tableSchema);
        sb.append(", ").append(tableName);
        sb.append(", ").append(id);

        sb.append(")");
        return sb.toString();
    }
}
