/*
 * This file is generated by jOOQ.
*/
package com.warumono.databases.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schemata implements Serializable {

    private static final long serialVersionUID = -665782295;

    private String  catalogName;
    private String  schemaName;
    private String  schemaOwner;
    private String  defaultCharacterSetName;
    private String  defaultCollationName;
    private Boolean isDefault;
    private String  remarks;
    private Integer id;

    public Schemata() {}

    public Schemata(Schemata value) {
        this.catalogName = value.catalogName;
        this.schemaName = value.schemaName;
        this.schemaOwner = value.schemaOwner;
        this.defaultCharacterSetName = value.defaultCharacterSetName;
        this.defaultCollationName = value.defaultCollationName;
        this.isDefault = value.isDefault;
        this.remarks = value.remarks;
        this.id = value.id;
    }

    public Schemata(
        String  catalogName,
        String  schemaName,
        String  schemaOwner,
        String  defaultCharacterSetName,
        String  defaultCollationName,
        Boolean isDefault,
        String  remarks,
        Integer id
    ) {
        this.catalogName = catalogName;
        this.schemaName = schemaName;
        this.schemaOwner = schemaOwner;
        this.defaultCharacterSetName = defaultCharacterSetName;
        this.defaultCollationName = defaultCollationName;
        this.isDefault = isDefault;
        this.remarks = remarks;
        this.id = id;
    }

    public String getCatalogName() {
        return this.catalogName;
    }

    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }

    public String getSchemaName() {
        return this.schemaName;
    }

    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName;
    }

    public String getSchemaOwner() {
        return this.schemaOwner;
    }

    public void setSchemaOwner(String schemaOwner) {
        this.schemaOwner = schemaOwner;
    }

    public String getDefaultCharacterSetName() {
        return this.defaultCharacterSetName;
    }

    public void setDefaultCharacterSetName(String defaultCharacterSetName) {
        this.defaultCharacterSetName = defaultCharacterSetName;
    }

    public String getDefaultCollationName() {
        return this.defaultCollationName;
    }

    public void setDefaultCollationName(String defaultCollationName) {
        this.defaultCollationName = defaultCollationName;
    }

    public Boolean getIsDefault() {
        return this.isDefault;
    }

    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Schemata (");

        sb.append(catalogName);
        sb.append(", ").append(schemaName);
        sb.append(", ").append(schemaOwner);
        sb.append(", ").append(defaultCharacterSetName);
        sb.append(", ").append(defaultCollationName);
        sb.append(", ").append(isDefault);
        sb.append(", ").append(remarks);
        sb.append(", ").append(id);

        sb.append(")");
        return sb.toString();
    }
}
