/*
 * This file is generated by jOOQ.
*/
package com.warumono.databases.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences implements Serializable {

    private static final long serialVersionUID = -1325620216;

    private String  sequenceCatalog;
    private String  sequenceSchema;
    private String  sequenceName;
    private Long    currentValue;
    private Long    increment;
    private Boolean isGenerated;
    private String  remarks;
    private Long    cache;
    private Long    minValue;
    private Long    maxValue;
    private Boolean isCycle;
    private Integer id;

    public Sequences() {}

    public Sequences(Sequences value) {
        this.sequenceCatalog = value.sequenceCatalog;
        this.sequenceSchema = value.sequenceSchema;
        this.sequenceName = value.sequenceName;
        this.currentValue = value.currentValue;
        this.increment = value.increment;
        this.isGenerated = value.isGenerated;
        this.remarks = value.remarks;
        this.cache = value.cache;
        this.minValue = value.minValue;
        this.maxValue = value.maxValue;
        this.isCycle = value.isCycle;
        this.id = value.id;
    }

    public Sequences(
        String  sequenceCatalog,
        String  sequenceSchema,
        String  sequenceName,
        Long    currentValue,
        Long    increment,
        Boolean isGenerated,
        String  remarks,
        Long    cache,
        Long    minValue,
        Long    maxValue,
        Boolean isCycle,
        Integer id
    ) {
        this.sequenceCatalog = sequenceCatalog;
        this.sequenceSchema = sequenceSchema;
        this.sequenceName = sequenceName;
        this.currentValue = currentValue;
        this.increment = increment;
        this.isGenerated = isGenerated;
        this.remarks = remarks;
        this.cache = cache;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.isCycle = isCycle;
        this.id = id;
    }

    public String getSequenceCatalog() {
        return this.sequenceCatalog;
    }

    public void setSequenceCatalog(String sequenceCatalog) {
        this.sequenceCatalog = sequenceCatalog;
    }

    public String getSequenceSchema() {
        return this.sequenceSchema;
    }

    public void setSequenceSchema(String sequenceSchema) {
        this.sequenceSchema = sequenceSchema;
    }

    public String getSequenceName() {
        return this.sequenceName;
    }

    public void setSequenceName(String sequenceName) {
        this.sequenceName = sequenceName;
    }

    public Long getCurrentValue() {
        return this.currentValue;
    }

    public void setCurrentValue(Long currentValue) {
        this.currentValue = currentValue;
    }

    public Long getIncrement() {
        return this.increment;
    }

    public void setIncrement(Long increment) {
        this.increment = increment;
    }

    public Boolean getIsGenerated() {
        return this.isGenerated;
    }

    public void setIsGenerated(Boolean isGenerated) {
        this.isGenerated = isGenerated;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Long getCache() {
        return this.cache;
    }

    public void setCache(Long cache) {
        this.cache = cache;
    }

    public Long getMinValue() {
        return this.minValue;
    }

    public void setMinValue(Long minValue) {
        this.minValue = minValue;
    }

    public Long getMaxValue() {
        return this.maxValue;
    }

    public void setMaxValue(Long maxValue) {
        this.maxValue = maxValue;
    }

    public Boolean getIsCycle() {
        return this.isCycle;
    }

    public void setIsCycle(Boolean isCycle) {
        this.isCycle = isCycle;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sequences (");

        sb.append(sequenceCatalog);
        sb.append(", ").append(sequenceSchema);
        sb.append(", ").append(sequenceName);
        sb.append(", ").append(currentValue);
        sb.append(", ").append(increment);
        sb.append(", ").append(isGenerated);
        sb.append(", ").append(remarks);
        sb.append(", ").append(cache);
        sb.append(", ").append(minValue);
        sb.append(", ").append(maxValue);
        sb.append(", ").append(isCycle);
        sb.append(", ").append(id);

        sb.append(")");
        return sb.toString();
    }
}
