/*
 * This file is generated by jOOQ.
*/
package com.warumono.databases.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeInfo implements Serializable {

    private static final long serialVersionUID = -877748097;

    private String  typeName;
    private Integer dataType;
    private Integer precision;
    private String  prefix;
    private String  suffix;
    private String  params;
    private Boolean autoIncrement;
    private Short   minimumScale;
    private Short   maximumScale;
    private Integer radix;
    private Integer pos;
    private Boolean caseSensitive;
    private Short   nullable;
    private Short   searchable;

    public TypeInfo() {}

    public TypeInfo(TypeInfo value) {
        this.typeName = value.typeName;
        this.dataType = value.dataType;
        this.precision = value.precision;
        this.prefix = value.prefix;
        this.suffix = value.suffix;
        this.params = value.params;
        this.autoIncrement = value.autoIncrement;
        this.minimumScale = value.minimumScale;
        this.maximumScale = value.maximumScale;
        this.radix = value.radix;
        this.pos = value.pos;
        this.caseSensitive = value.caseSensitive;
        this.nullable = value.nullable;
        this.searchable = value.searchable;
    }

    public TypeInfo(
        String  typeName,
        Integer dataType,
        Integer precision,
        String  prefix,
        String  suffix,
        String  params,
        Boolean autoIncrement,
        Short   minimumScale,
        Short   maximumScale,
        Integer radix,
        Integer pos,
        Boolean caseSensitive,
        Short   nullable,
        Short   searchable
    ) {
        this.typeName = typeName;
        this.dataType = dataType;
        this.precision = precision;
        this.prefix = prefix;
        this.suffix = suffix;
        this.params = params;
        this.autoIncrement = autoIncrement;
        this.minimumScale = minimumScale;
        this.maximumScale = maximumScale;
        this.radix = radix;
        this.pos = pos;
        this.caseSensitive = caseSensitive;
        this.nullable = nullable;
        this.searchable = searchable;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public Integer getDataType() {
        return this.dataType;
    }

    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    public Integer getPrecision() {
        return this.precision;
    }

    public void setPrecision(Integer precision) {
        this.precision = precision;
    }

    public String getPrefix() {
        return this.prefix;
    }

    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    public String getSuffix() {
        return this.suffix;
    }

    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    public String getParams() {
        return this.params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public Boolean getAutoIncrement() {
        return this.autoIncrement;
    }

    public void setAutoIncrement(Boolean autoIncrement) {
        this.autoIncrement = autoIncrement;
    }

    public Short getMinimumScale() {
        return this.minimumScale;
    }

    public void setMinimumScale(Short minimumScale) {
        this.minimumScale = minimumScale;
    }

    public Short getMaximumScale() {
        return this.maximumScale;
    }

    public void setMaximumScale(Short maximumScale) {
        this.maximumScale = maximumScale;
    }

    public Integer getRadix() {
        return this.radix;
    }

    public void setRadix(Integer radix) {
        this.radix = radix;
    }

    public Integer getPos() {
        return this.pos;
    }

    public void setPos(Integer pos) {
        this.pos = pos;
    }

    public Boolean getCaseSensitive() {
        return this.caseSensitive;
    }

    public void setCaseSensitive(Boolean caseSensitive) {
        this.caseSensitive = caseSensitive;
    }

    public Short getNullable() {
        return this.nullable;
    }

    public void setNullable(Short nullable) {
        this.nullable = nullable;
    }

    public Short getSearchable() {
        return this.searchable;
    }

    public void setSearchable(Short searchable) {
        this.searchable = searchable;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TypeInfo (");

        sb.append(typeName);
        sb.append(", ").append(dataType);
        sb.append(", ").append(precision);
        sb.append(", ").append(prefix);
        sb.append(", ").append(suffix);
        sb.append(", ").append(params);
        sb.append(", ").append(autoIncrement);
        sb.append(", ").append(minimumScale);
        sb.append(", ").append(maximumScale);
        sb.append(", ").append(radix);
        sb.append(", ").append(pos);
        sb.append(", ").append(caseSensitive);
        sb.append(", ").append(nullable);
        sb.append(", ").append(searchable);

        sb.append(")");
        return sb.toString();
    }
}
