/*
 * This file is generated by jOOQ.
*/
package com.warumono.databases.information_schema.tables;


import com.warumono.databases.information_schema.InformationSchema;
import com.warumono.databases.information_schema.tables.records.SessionStateRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionState extends TableImpl<SessionStateRecord> {

    private static final long serialVersionUID = -454644384;

    /**
     * The reference instance of <code>INFORMATION_SCHEMA.SESSION_STATE</code>
     */
    public static final SessionState SESSION_STATE = new SessionState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SessionStateRecord> getRecordType() {
        return SessionStateRecord.class;
    }

    /**
     * The column <code>INFORMATION_SCHEMA.SESSION_STATE.KEY</code>.
     */
    public final TableField<SessionStateRecord, String> KEY = createField("KEY", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>INFORMATION_SCHEMA.SESSION_STATE.SQL</code>.
     */
    public final TableField<SessionStateRecord, String> SQL = createField("SQL", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * Create a <code>INFORMATION_SCHEMA.SESSION_STATE</code> table reference
     */
    public SessionState() {
        this("SESSION_STATE", null);
    }

    /**
     * Create an aliased <code>INFORMATION_SCHEMA.SESSION_STATE</code> table reference
     */
    public SessionState(String alias) {
        this(alias, SESSION_STATE);
    }

    private SessionState(String alias, Table<SessionStateRecord> aliased) {
        this(alias, aliased, null);
    }

    private SessionState(String alias, Table<SessionStateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return InformationSchema.INFORMATION_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionState as(String alias) {
        return new SessionState(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SessionState rename(String name) {
        return new SessionState(name, null);
    }
}
